<?php
session_start();
$_SESSION["SFZ"] = "3200";
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>重走青春路 - 拖拉网</title>
<link href="src/css/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript"> 
window.onload=function(){ 
for(var ii=0; ii<document.links.length; ii++) document.links[ii].onfocus=function(){this.blur()} 
} 
</script>
</head>
 
<body id="ztBodyBg">
<div id="ztcontainer">
    <div id="ztcontent">
        <div class="BG1">
        	<div class="head">
            	<div class="head1 left">
                	<a href="http://www.tuolar.com" title="拖拉网" class="logo"><img src="src/images/img_start_03.jpg"/></a>
                    <img class="s1" src="src/images/img_start_06.jpg"/>
                </div>
                <div class="head2 ">
                	<h1>重走青春路</h1>
                    <img class="s2" src="src/images/img_start_09.jpg"/>
                </div>
            </div>
            <div class="content">
            	<div class="d1">
                	<img class="m1" src="src/images/image_15.jpg"/>
                    <div class="d2">
                    	<p class="p1">回想青春，你是否也留有遗憾，想要重走青春路？想知道要做什么才能重走青春路吗？马上就来测测吧。</p>
                        <a href="main.php" ><img src="src/images/image_18.jpg"/></a>
                    </div>
                </div>
            </div>
        </div>            
  	</div>
</div>

</body>
</html>
