<?php
header('Content-type: text/html; charset=utf-8');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>美装艳遇老虎机 - 拖拉网</title>
<style>
body{background:#D8006C url("<?php echo APP_SINA_URL;?>src/img/wrapBg.jpg") repeat; color: #666666;font: 12px/20px '微软雅黑','Tahoma','Geneva','sans-serif';}
p{height:22px;line-height:22px;}
span{font-size:15px;font-weight:bold;}
a{color:#555454;text-decoration:none;}
a:hover,a:active,a:focus{ text-decoration:underline;}
</style>
</head>
<body>
<div style="margin:0 auto; width:760px; position:relative;">
	<div style="margin:250px 0" align="center">
		<div style="border: 4px solid #efefef;color:#666;background: none repeat scroll 0 0 #FFFFFF;display:block;z-index:100;height:130px;width:400px;">
		<p>^_^ 你已关注拖拉网!</p>
		<p>可以第一时间获知更多好玩有趣的时尚搭配哦!</p>
		<p><a href="<?php echo SINA_APP_CALLBACK;?>"><span>继续测试</span></a> or <a href="http://weibo.com/tuolar" target="_blank"><span>去拖拉网微博看看</span></a></p>
		</div>
	</div>
</div>
</body>
</html>