<?php
header('Content-type: text/html; charset=utf-8');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>美装艳遇老虎机 - 拖拉网</title>
<link href="<?php echo APP_SINA_URL;?>src/css/main.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo APP_SINA_URL;?>src/js/jquery-1.4.2.min.js"></script>
<!--[if IE 6]>
<script type="text/javascript" src="<?php echo APP_SINA_URL;?>src/js/DD_belatedPNG_0.0.8a.js"></script>
<script type="text/javascript">DD_belatedPNG.fix('.pngFix');</script>
<![endif]-->
</head>
<body>
<?php echo $this->content; ?>
</body>
</html>
