<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>重走青春路 - 拖拉网</title>
<link href="src/css/style1.css" rel="stylesheet" type="text/css" />
<script type="text/javascript"> 
window.onload=function(){ 
for(var ii=0; ii<document.links.length; ii++) document.links[ii].onfocus=function(){this.blur()} 
} 
</script>
</head>
 
<body id="ztBodyBg">
<div id="ztcontainer">
    <div id="ztcontent">
        <div class="BG2">
        	<div class="head">
            	<a class="logo" title="拖拉网" href="http://tuolar.com" target="_blank"><img src="src/images/haha_03.jpg"/></a>
                <p class="p1"><a href="http://tuolar.com" target="_blank" title="拖拉网">更多精彩内容>></a></p>
            </div>
            <div class="content">
            	<img class="m1" src="<?php echo $_SESSION['show']['pic_url'];?>"/>
                <p class="p2"><?php echo $_SESSION['show']['showContent'];?><?php if($_SESSION['add']['ret']!=0):?><br />抱歉，发送微博失败。<?php endif;?></p>
            </div>
        </div>           
  	</div>
  
</div>

</body>
</html>